### ISSUE TITLE
Hentai Foundry 404

### ISSUE THREAD

**Issue by ChickenOfDoom** [4pr0n/ripme#157]
Trying to download an artist's Hentai Foundry gallery results in 404 errors. This seems to be caused by line 79 in the HF ripper, where there's an extra slash at the end of the URL string.

**Comment by Doleman** [comment]
Does the log look something along the lines of this?
2015-01-21 22:29:03,468 ERROR ripper.AbstractRipper  - Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.HentaifoundryRipper.getNextPage(HentaifoundryRipper.java:76)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:103)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:327)
	at java.lang.Thread.run(Unknown Source)
2015-01-21 22:29:03,805 ERROR ripper.DownloadFileThread  - [!] Non-retriable status code 404 while downloading from http://pictures.hentai-foundry.com//s/Svenners/322667.jpg

I found this to happen when it tries to download .png as a .jpg

**Comment by ChickenOfDoom** [comment]
Ah, I should have tested it on more than gallery! The errors I get look like this:
2015-01-21 13:46:06,999 ERROR ripper.DownloadFileThread  - [!] Non-retriable status code 404 while downloading from http://pictures.hentai-foundry.com//o/Octoboy/289548.jpg

**Comment by 4pr0n** [comment]
Yep, that's a `png` but it thinks it's a `jpg`. Looks like a bug.
