### ISSUE TITLE
java.awt.HeadlessException

### ISSUE THREAD

**Issue by clb92** [4pr0n/ripme#164]
I tried to run `ripme` on my Synology DS415play NAS, but I get this error:

    DiskStation> java -jar /volume1/downloads/ripme/ripme.jar
    Loaded file:/volume1/downloads/ripme/ripme.jar!/rip.properties
    Loaded log4j.properties
    Initialized ripme v1.0.91
    Exception in thread "main" java.awt.HeadlessException:
    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
            at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
            at java.awt.Window.<init>(Window.java:535)
            at java.awt.Frame.<init>(Frame.java:420)
            at javax.swing.JFrame.<init>(JFrame.java:224)
            at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:138)
            at com.rarchives.ripme.App.main(App.java:39)

I tried newest version too (1.1.4), but with same result.
Is there any way I can force `ripme` to run in headless mode?

**Comment by clb92** [comment]
I somehow fixed it. I think it had to do with the way I executed `ripme` from my PHP script.

Here's how I do it now:

    shell_exec('cd /volume1/downloads/ripme/ && java -jar /volume1/downloads/ripme/ripme.jar -u ' . $source . ' 2>&1');
