### ISSUE TITLE
Cannot run ripme.jar with SE 31 installed

### ISSUE THREAD

**Issue by Aphetoros** [4pr0n/ripme#170]
I installed a fresh copy of Java SE 31 and try double clicking the .jar file and nothing happens. So I went to the command line and tried running directly from there; I get this list of errors.

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\Users\User\Desktop

C:\Users\User\Desktop>java -jar ripme.jar
log4j:ERROR Could not read configuration file from URL [jar:file:/C:/Users/Apollo!/Desktop/ripme.jar!/log4j.properties].
java.io.FileNotFoundException: C:\Users\User (The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at com.rarchives.ripme.utils.Utils.<clinit>(Utils.java:37)
        at com.rarchives.ripme.App.main(App.java:30)
log4j:ERROR Ignoring configuration file [jar:file:/C:/Users/User/Desktop/ripme.jar!/log4j.properties].
log4j:WARN No appenders could be found for logger (org.apache.commons.configuration.PropertiesConfiguration).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at com.rarchives.ripme.utils.Utils.getConfigBoolean(Utils.java:85)
        at com.rarchives.ripme.utils.Utils.configureLogger(Utils.java:323)
        at com.rarchives.ripme.App.main(App.java:30)

C:\Users\User\Desktop>
```

**Comment by 4pr0n** [comment]
Yikes. What version of java are you running?

In the command-line, type `java -version`

**Comment by Aphetoros** [comment]
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\User>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode, sharing)
```
Weird thing is I tried running ripme on my laptop and everything works. Not sure why it's not on here.

**Comment by 4pr0n** [comment]
Java 8, eh. Hm. I'll need to test this on my windows box.

**Comment by Aphetoros** [comment]
My laptop's running the older version no problems

```
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) Client VM (build 25.11-b03, mixed mode, sharing)
```

**Comment by 4pr0n** [comment]
Don't think it's due to Java8...

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\win7>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode, sharing)

C:\Users\win7>cd Downloads

C:\Users\win7\Downloads>java -jar ripme.jar
Loaded C:\Users\win7\Downloads\rip.properties
Loaded log4j.properties
Initialized ripme v1.1.6
```

**Comment by 4pr0n** [comment]
Questions:
* The `ripme.jar` file ... is that the latest version from the site? http://rarchives.com/ripme.jar

If not, try the latest version.

If so, try an older version... http://rarchives.com/ripme.jar.1.1.0 (rename to `ripme.jar`)

Apparently `maven` can create some faulty build files, so there's a chance that the version on the site is a 'bad build'; or an older version is a 'bad build'.

**Comment by Aphetoros** [comment]
Yeah I think my system is the problem. Thanks for the help though! :) Really appreciate it!

**Comment by 4pr0n** [comment]
:( ok. Remember to post back here if you fix it...
