### ISSUE TITLE
Can't download single Imgur images, only abums?

### ISSUE THREAD

**Issue by clb92** [4pr0n/ripme#187]
If I give Ripme an Imgur URL like this `http://imgur.com/oiifnQh` or `http://i.imgur.com/oiifnQh.gif` it returns this error:

    Initialized ripme v1.1.4
    [!] Error while ripping URL http://i.imgur.com/1q3DTZg.gif
    java.lang.Exception: No compatible ripper found
    	at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:288)
    	at com.rarchives.ripme.App.rip(App.java:45)
    	at com.rarchives.ripme.App.handleArguments(App.java:101)
    	at com.rarchives.ripme.App.main(App.java:37)

Are non-album Imgur images really not supported?

**Comment by pic4share** [comment]
http://www.pic4share.com/particularpic.php?id=MTIw

**Comment by pic4share** [comment]
http://www.pic4share.com/snapmessagepic.php

**Comment by aardvaark** [comment]
I agree, this this should be looked into. Not being able to rip direct imgur link seems kind of silly. 
The problem is pronounced when you have a batch of direct imgur links but would have to otherwise manually goto each link and save them

**Comment by madcrow** [comment]
+1

**Comment by metaprime** [comment]
Agreed, especially with the introduction of #344 being able to take a list of imgur single-image page links and rip them would be helpful.
