### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out [v1.1.7]

### ISSUE THREAD

**Issue by ohhdemgirls** [4pr0n/ripme#191]
While doing `java -jar ripme.jar -u https://www.reddit.com/user/teenage_waistband`

```
Error while loading http://www.reddit.com/user/teenage_waistband.json?after=t1_cprrjuu
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:453)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:129)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:121)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:71)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:60)
	at com.rarchives.ripme.App.rip(App.java:47)
	at com.rarchives.ripme.App.handleArguments(App.java:101)
	at com.rarchives.ripme.App.main(App.java:37)
[!] Error while ripping URL http://www.reddit.com/user/teenage_waistband
java.io.IOException: Failed to load http://www.reddit.com/user/teenage_waistband.json?after=t1_cprrjuu after 1 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:136)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:121)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:71)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:60)
	at com.rarchives.ripme.App.rip(App.java:47)
	at com.rarchives.ripme.App.handleArguments(App.java:101)
	at com.rarchives.ripme.App.main(App.java:37)
```

**Comment by 4pr0n** [comment]
Might be related to http://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

Need to migrate RipMe (and every other damn repo) to use OAuth2 before talking to reddit. Ugh.

**Comment by 4pr0n** [comment]
Update to `1.1.8`. Seems to work for me, but we'll see what happens when *everyone* starts using `1.1.8`...
