### ISSUE TITLE
Instagram Rip no longer works

### ISSUE THREAD

**Issue by Hydrobolt** [4pr0n/ripme#208]
So Iconosquare has updated their site and somehow ripping through the site has stopped. Trying to rip instagram profiles leads to "Unable to fine User ID at <insert URL>"
 Example using a public page: http://iconosquare.com/marvel

**Comment by ohhdemgirls** [comment]
I secondthis 

```
Loaded /home/ohhdemgirls/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.1.8
Retrieving http://iconosquare.com/missphitran
[!] Error while ripping URL https://instagram.com/missphitran/
java.io.IOException: Unable to find userID at http://iconosquare.com/missphitran
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getUserID(InstagramRipper.java:103)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getFirstPage(InstagramRipper.java:108)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:54)
	at com.rarchives.ripme.App.rip(App.java:47)
	at com.rarchives.ripme.App.handleArguments(App.java:101)
	at com.rarchives.ripme.App.main(App.java:37)
```

**Comment by dj2bee** [comment]
I fixed this issue in my [fork](https://github.com/dj2bee/ripme/commit/a85cd9d01fd8f5e9ce698673d06464149033e8b8).

Iconosquare changed the url from `iconosquare.com/user/xyz` to `iconosquare.com/xyz`. You simple need to fix the url in [InstagramRipper.java](https://github.com/4pr0n/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java)

**Comment by Reddman** [comment]
Good job DJ
