### ISSUE TITLE
Unable to rip Twitter

### ISSUE THREAD

**Issue by boobiebrat** [4pr0n/ripme#251]
I am unable to rip twitter media from a long time now. Every time I try to rip twitter media I get an error saying "no compatible ripper found". I did download the latest source file and compile the jar file, but still in vain. Pasted below is the log message from the log file. Hope this is resolved soon.

2015-09-30 02:40:41,555 ERROR ui.MainWindow .ripAlbum() Could not find ripper for URL https://twitter.com/easports
java.lang.Exception: No compatible ripper found
	at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:295)
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1040)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:999)
	at com.rarchives.ripme.ui.MainWindow.access$3400(MainWindow.java:79)
	at com.rarchives.ripme.ui.MainWindow$23.intervalAdded(MainWindow.java:748)
	at javax.swing.AbstractListModel.fireIntervalAdded(Unknown Source)
	at javax.swing.DefaultListModel.add(Unknown Source)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1075)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by TheDuck1234** [comment]
I have the same problem just with imgur
```
2015-10-08 11:37:17,325 ERROR ui.MainWindow .ripAlbum() Could not find ripper for URL http://imgur.com/gallery/cV6Rr
java.lang.Exception: No compatible ripper found
	at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:295)
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1040)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:999)
	at com.rarchives.ripme.ui.MainWindow.access$3400(MainWindow.java:79)
	at com.rarchives.ripme.ui.MainWindow$23.intervalAdded(MainWindow.java:748)
	at javax.swing.AbstractListModel.fireIntervalAdded(Unknown Source)
	at javax.swing.DefaultListModel.add(Unknown Source)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1075)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by version365** [comment]
@TheDuck1234 Imgur gallery links are not supported. Put 'a' in the place of 'gallery' in the link (without quotes).. everything will be ok..

**Comment by TheDuck1234** [comment]
@version365 when how do i make it download the whole gallery ? when i change it to "a" i only downloads the first 10 image in there.

**Comment by Hrxn** [comment]
Does the download link provided by imgur work?

**Comment by 4pr0n** [comment]
1. The imgur "first 10 images" issue was fixed. I'll push an update to handle `/gallery/` URLs.
2. I was able to rip the twitter link `https://twitter.com/easports` without any problems.

Closing this, but feel free to reopen if there's still issues.
