### ISSUE TITLE
Instagram: ["standard_resolution"] is not a JSONObject.

### ISSUE THREAD

**Issue by ohhdemgirls** [4pr0n/ripme#598]
Reproduce with `java -jar ripme.jar -u https://www.instagram.com/laurenscolari/`

```
[!] Error while ripping URL https://www.instagram.com/laurenscolari/
org.json.JSONException: JSONObject["standard_resolution"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:577)
        at com.rarchives.ripme.ripper.rippers.InstagramRipper.getMedia(InstagramRipper.java:128)
        at com.rarchives.ripme.ripper.rippers.InstagramRipper.getURLsFromJSON(InstagramRipper.java:154)
        at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:57)
        at com.rarchives.ripme.App.rip(App.java:59)
        at com.rarchives.ripme.App.ripURL(App.java:169)
        at com.rarchives.ripme.App.handleArguments(App.java:161)
        at com.rarchives.ripme.App.main(App.java:49)
```

**Comment by rautamiekka** [comment]
Please reopen at https://github.com/RipMeApp/ripme/issues/, mentioning it's originally this one.

**Comment by varaghar** [comment]
I would like to start this!

**Comment by rautamiekka** [comment]
For the record, I've no problems ripping this, so I think it was an error on Instagram's end.

Window$ 7 Ultimate SP1 x64
Oracle Java SE 8 Update 144 x64
RipMe 1.5.7

**Comment by varaghar** [comment]
It does throw an exception here. I will add some checks so this won't cause any more issues.

**Comment by rautamiekka** [comment]
^ What're you running ? Like I just listed.

**Comment by metaprime** [comment]
Merged fix.
