### ISSUE TITLE
Bug: RejectedExecutionException 

### ISSUE THREAD

**Issue by whyamibeer** [4pr0n/ripme#80]
Exception:
Exception in thread "pool-2-thread-4136" java.util.concurrent.RejectedExecutionException: Task Thread[Thread-169720,5,main] rejected from java.util.concurrent.ThreadPoolExecutor@4fdf02ff[Shutting down, pool size = 5, active threads = 5, queued tasks = 12242, completed tasks = 24432]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
    at com.rarchives.ripme.ripper.DownloadThreadPool.addThread(DownloadThreadPool.java:34)
    at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:57)
    at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:131)
    at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:144)
    at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:157)
    at com.rarchives.ripme.ripper.rippers.FlickrRipper$FlickrImageThread.run(FlickrRipper.java:253)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

The ripper keeps dieing on me when trying to rip a 160k image flicker account (https://www.flickr.com/photos/herosjourneymythology45surf/) full of massive pictures which are sometimes (but rarely) over 100mb (already changed the max file size to higher than this limit).  I've gotten the first 20k or so pictures from it, but when I restart the program it throws 20k warnings for duplicate pictures, then downloads a few hundred pictures, then errors out with the exception above.  When I say it errors out, I mean the logger that outputs to the console spams the shit out of that error, but the UI just pretends nothing is happening.  The log there just stops being updated.

**Comment by disruptive-orange** [comment]
I get the same error as op in my own ripper if I don't add a 300ms delay after every single thread added to the pool. Why is this?
